/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.phoenix.stockproducer.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductStock extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3970812996135149396L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductStock\",\"namespace\":\"com.phoenix.stockproducer.schema\",\"fields\":[{\"name\":\"sku\",\"type\":\"int\"},{\"name\":\"quantity\",\"type\":\"long\"},{\"name\":\"locationName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductStock> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductStock> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductStock> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductStock> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductStock> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductStock to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductStock from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductStock instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductStock fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int sku;
  private long quantity;
  private java.lang.CharSequence locationName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductStock() {}

  /**
   * All-args constructor.
   * @param sku The new value for sku
   * @param quantity The new value for quantity
   * @param locationName The new value for locationName
   */
  public ProductStock(java.lang.Integer sku, java.lang.Long quantity, java.lang.CharSequence locationName) {
    this.sku = sku;
    this.quantity = quantity;
    this.locationName = locationName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sku;
    case 1: return quantity;
    case 2: return locationName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sku = (java.lang.Integer)value$; break;
    case 1: quantity = (java.lang.Long)value$; break;
    case 2: locationName = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public int getSku() {
    return sku;
  }


  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(int value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public long getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(long value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'locationName' field.
   * @return The value of the 'locationName' field.
   */
  public java.lang.CharSequence getLocationName() {
    return locationName;
  }


  /**
   * Sets the value of the 'locationName' field.
   * @param value the value to set.
   */
  public void setLocationName(java.lang.CharSequence value) {
    this.locationName = value;
  }

  /**
   * Creates a new ProductStock RecordBuilder.
   * @return A new ProductStock RecordBuilder
   */
  public static com.phoenix.stockproducer.schema.ProductStock.Builder newBuilder() {
    return new com.phoenix.stockproducer.schema.ProductStock.Builder();
  }

  /**
   * Creates a new ProductStock RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductStock RecordBuilder
   */
  public static com.phoenix.stockproducer.schema.ProductStock.Builder newBuilder(com.phoenix.stockproducer.schema.ProductStock.Builder other) {
    if (other == null) {
      return new com.phoenix.stockproducer.schema.ProductStock.Builder();
    } else {
      return new com.phoenix.stockproducer.schema.ProductStock.Builder(other);
    }
  }

  /**
   * Creates a new ProductStock RecordBuilder by copying an existing ProductStock instance.
   * @param other The existing instance to copy.
   * @return A new ProductStock RecordBuilder
   */
  public static com.phoenix.stockproducer.schema.ProductStock.Builder newBuilder(com.phoenix.stockproducer.schema.ProductStock other) {
    if (other == null) {
      return new com.phoenix.stockproducer.schema.ProductStock.Builder();
    } else {
      return new com.phoenix.stockproducer.schema.ProductStock.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductStock instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductStock>
    implements org.apache.avro.data.RecordBuilder<ProductStock> {

    private int sku;
    private long quantity;
    private java.lang.CharSequence locationName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.phoenix.stockproducer.schema.ProductStock.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.locationName)) {
        this.locationName = data().deepCopy(fields()[2].schema(), other.locationName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductStock instance
     * @param other The existing instance to copy.
     */
    private Builder(com.phoenix.stockproducer.schema.ProductStock other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.locationName)) {
        this.locationName = data().deepCopy(fields()[2].schema(), other.locationName);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public int getSku() {
      return sku;
    }


    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder setSku(int value) {
      validate(fields()[0], value);
      this.sku = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder clearSku() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public long getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder setQuantity(long value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocationName() {
      return locationName;
    }


    /**
      * Sets the value of the 'locationName' field.
      * @param value The value of 'locationName'.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder setLocationName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.locationName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'locationName' field has been set.
      * @return True if the 'locationName' field has been set, false otherwise.
      */
    public boolean hasLocationName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'locationName' field.
      * @return This builder.
      */
    public com.phoenix.stockproducer.schema.ProductStock.Builder clearLocationName() {
      locationName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductStock build() {
      try {
        ProductStock record = new ProductStock();
        record.sku = fieldSetFlags()[0] ? this.sku : (java.lang.Integer) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Long) defaultValue(fields()[1]);
        record.locationName = fieldSetFlags()[2] ? this.locationName : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductStock>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductStock>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductStock>
    READER$ = (org.apache.avro.io.DatumReader<ProductStock>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.sku);

    out.writeLong(this.quantity);

    out.writeString(this.locationName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sku = in.readInt();

      this.quantity = in.readLong();

      this.locationName = in.readString(this.locationName instanceof Utf8 ? (Utf8)this.locationName : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sku = in.readInt();
          break;

        case 1:
          this.quantity = in.readLong();
          break;

        case 2:
          this.locationName = in.readString(this.locationName instanceof Utf8 ? (Utf8)this.locationName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










